name: Pre-Deploy  Workflow
inputs:
  env:
    default: dev
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 1
    - uses: actions/download-artifact@v4
      with:
        name: DeployArtifact
        path: deploy
    - name: Dummy Pre-deploy 
      shell: bash
      run: |
        echo "This is a pre-deploy step "
        ls -la 
        ls -la deploy/
    - name: Dummy Deploy Step
      shell: bash
      run: |
        echo "Check for env"                
        echo ${{ inputs.env }}
        echo "What build number?"
        cat deploy/buildNumber.txt
        echo "Do we have the env vars?"
        cat deploy/environment.txt | wc -l 
        
