name: Test Build Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      var1:
        description: 'The firt variable'
        required: false
        type: string
      var2:
        description: 'The second variable'
        required: false
        type: string


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read
  actions: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - name: Dummy build check
              run: |
                echo "This is the build step "
            - name: Make Deploy files
              run: |
                DATE=$(date)
                echo ${DATE} > deploy/date-time.txt
            - name: Create Deploy Artifact
              uses: actions/upload-artifact@v4
              with:
                name: DeployArtifact
                path: deploy/
                if-no-files-found: error