name: Testing Full Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:
  pull_request: 


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  packages: read
  actions: read

jobs: 
  # build-and-test: 
  #   uses: DnDBeyond/waterdeep-web/.github/workflows/_build-and-test.yml@feat/github-actions-1
  #   secrets: inherit
  #   #  with: # no inputs
  build: 
    uses: andersb1-wotc/actions-testing-env/.github/workflows/_build.yml@main
    secrets: inherit
    with: 
      var1: 'foo'
      var2: 'bar'
  # pre-deploy-stg: 
  #   # if: github.event.pull_request.merged == true
  #   uses: andersb1-wotc/actions-testing-env/.github/workflows/_pre-deploy.yml@main
  #   needs: [ build ] 
  #   secrets: inherit
  #   with:
  #     env: stg
  deploy-stg: 
    # if: github.event.pull_request.merged == true
    uses: andersb1-wotc/actions-testing-env/.github/workflows/_deploy.yml@main
    needs: [ build ] 
    secrets: inherit
    with:
      env: stg
  # pre-deploy-live: 
  #   # if: github.event.pull_request.merged == true
  #   uses: andersb1-wotc/actions-testing-env/.github/workflows/_pre-deploy.yml@main
  #   needs: [ build ] 
  #   secrets: inherit
  #   with:
  #     env: live
  deploy-live: 
    uses: andersb1-wotc/actions-testing-env/.github/workflows/_deploy.yml@main
    needs: [ build, deploy-stg  ] 
    secrets: inherit
    with:
      env: live
